const INTERNAL_STATUS_CODE = {
  SUCCESS: 0,
  CONFLICT: 1,
  NOT_FOUND: 101,
  BAD_REQUEST: 102,
  INVALID_CREDENTIALS: 103,
  UNAUTHORIZED: 108,
  SERVER_ERROR: 109,
} as const;

export {INTERNAL_STATUS_CODE};
